#ifndef CID_V1_H
#define CID_V1_H

#include <stddef.h>
#include <stdint.h>

#include "multiformats/multibase/multibase.h"

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @file cid_v1.h
 * @brief CIDv1 public API.
 *
 * CIDv1 binary layout:
 *   <varint(version=1)><varint(codec)><multihash>
 *
 * CIDv1 string layout:
 *   <multibase-prefix><encoded-binary-cidv1>
 */

/** @brief CIDv1 version value. */
#define CIDV1_VERSION ((uint64_t)1U)

/** @brief Maximum encoded varint bytes supported by this project (63-bit values). */
#define CIDV1_MAX_VARINT_SIZE ((size_t)9U)

/**
 * @brief Maximum accepted multihash size for CIDv1 operations.
 *
 * This bound keeps stack and parsing behavior deterministic while covering
 * practical digest sizes used in this repository.
 */
#define CIDV1_MAX_MULTIHASH_SIZE ((size_t)512U)

/** @brief Maximum CIDv1 binary size accepted/generated by this module. */
#define CIDV1_MAX_BINARY_SIZE ((size_t)((CIDV1_MAX_VARINT_SIZE * 2U) + CIDV1_MAX_MULTIHASH_SIZE))

/** @brief Common codec constants used by tests and human-readable conversion. */
#define CIDV1_CODEC_RAW ((uint64_t)0x55U)
#define CIDV1_CODEC_DAG_PB ((uint64_t)0x70U)

/** @brief Common multihash code constants used by human-readable conversion. */
#define CIDV1_MH_CODE_IDENTITY ((uint64_t)0x00U)
#define CIDV1_MH_CODE_SHA2_256 ((uint64_t)0x12U)
#define CIDV1_MH_CODE_SHA2_512 ((uint64_t)0x13U)
#define CIDV1_MH_CODE_SHA3_512 ((uint64_t)0x14U)
#define CIDV1_MH_CODE_SHA3_384 ((uint64_t)0x15U)
#define CIDV1_MH_CODE_SHA3_256 ((uint64_t)0x16U)
#define CIDV1_MH_CODE_SHA3_224 ((uint64_t)0x17U)

/**
 * @brief Error-code type for CIDv1 operations.
 */
typedef int cidv1_error_t;

#define CIDV1_SUCCESS ((cidv1_error_t)0)
#define CIDV1_ERROR_NULL_POINTER ((cidv1_error_t) - 1)
#define CIDV1_ERROR_INVALID_ARG ((cidv1_error_t) - 2)
#define CIDV1_ERROR_BUFFER_TOO_SMALL ((cidv1_error_t) - 3)
#define CIDV1_ERROR_ENCODE_FAILURE ((cidv1_error_t) - 4)
#define CIDV1_ERROR_DECODE_FAILURE ((cidv1_error_t) - 5)

/**
 * @brief Represents a CIDv1.
 *
 * `multihash` points to `multihash_storage` when initialized successfully.
 * The storage is owned by the struct itself and requires no heap allocation.
 */
typedef struct
{
	uint64_t version;
	uint64_t codec;
	uint8_t multihash_storage[CIDV1_MAX_MULTIHASH_SIZE];
	uint8_t *multihash;
	size_t multihash_size;
} cid_v1_t;

/**
 * @brief Initialize a CIDv1 with codec and multihash bytes.
 *
 * @param[out] cid           Destination CID object.
 * @param[in]  content_codec CID content codec.
 * @param[in]  mh_data       Multihash bytes.
 * @param[in]  mh_size       Number of bytes in @p mh_data.
 *
 * @return @ref CIDV1_SUCCESS on success, or negative error code.
 */
int cid_v1_init(cid_v1_t *cid, uint64_t content_codec, const uint8_t *mh_data, size_t mh_size);

/**
 * @brief Reset CIDv1 object to an empty state.
 *
 * @param[in,out] cid CID object to clear.
 *
 * @note Safe to call with `cid == NULL`.
 */
void cid_v1_free(cid_v1_t *cid);

/**
 * @brief Parse CIDv1 from binary bytes.
 *
 * @param[out] cid       Destination CID object.
 * @param[in]  data      Input bytes.
 * @param[in]  data_len  Input length.
 *
 * @return Bytes consumed on success, or negative error code.
 *
 * @note On failure (except NULL-pointer failure), @p cid is reset.
 */
ptrdiff_t cid_v1_from_bytes(cid_v1_t *cid, const uint8_t *data, size_t data_len);

/**
 * @brief Encode CIDv1 to binary bytes.
 *
 * @param[in]  cid      Source CID object.
 * @param[out] out      Output buffer.
 * @param[in]  out_len  Output buffer size.
 *
 * @return Bytes written on success, or negative error code.
 */
ptrdiff_t cid_v1_to_bytes(const cid_v1_t *cid, uint8_t *out, size_t out_len);

/**
 * @brief Encode CIDv1 to multibase string.
 *
 * @param[in]  cid      Source CID object.
 * @param[in]  base     Output multibase.
 * @param[out] out      Output string buffer.
 * @param[in]  out_len  Output buffer size.
 *
 * @return Characters written (excluding null terminator) on success,
 *         or negative error code.
 *
 * @note On failure (except NULL-pointer failure), and when @p out_len > 0,
 * `out[0]` is set to `\0`.
 */
ptrdiff_t cid_v1_to_string(const cid_v1_t *cid, multibase_t base, char *out, size_t out_len);

/**
 * @brief Decode CIDv1 from multibase string.
 *
 * @param[out] cid Destination CID object.
 * @param[in]  str Null-terminated CID string.
 *
 * @return Characters consumed on success, or negative error code.
 *
 * @note On failure (except NULL-pointer failure), @p cid is reset.
 */
ptrdiff_t cid_v1_from_string(cid_v1_t *cid, const char *str);

/**
 * @brief Convert CIDv1 to human-readable form:
 *
 * `<multibase-name> - cidv1 - <codec-name> - <multihash-name>-<hex-digest>`
 *
 * @param[in]  cid      Source CID object.
 * @param[in]  base     Preferred multibase name for output prefix section.
 * @param[out] out      Output string buffer.
 * @param[in]  out_len  Output buffer size.
 *
 * @return Characters written (excluding null terminator) on success,
 *         or negative error code.
 *
 * @note On failure (except NULL-pointer failure), and when @p out_len > 0,
 * `out[0]` is set to `\0`.
 */
ptrdiff_t cid_v1_to_human(const cid_v1_t *cid, multibase_t base, char *out, size_t out_len);

#ifdef __cplusplus
}
#endif

#endif /* CID_V1_H */
